# Generated by Django 6.0.3 on 2026-03-27 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('flag_emoji', models.CharField(max_length=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProficiencyLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('label', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField()),
                ('min_xp', models.PositiveIntegerField(default=0)),
                ('max_xp', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
