# Generated by Django 6.0.3 on 2026-03-27 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('decks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repetitions', models.PositiveIntegerField(default=0)),
                ('ease_factor', models.FloatField(default=2.5)),
                ('interval_days', models.PositiveIntegerField(default=0)),
                ('next_review', models.DateField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('flashcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_progresses', to='decks.flashcard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_progresses', to='accounts.languagelearner')),
            ],
            options={
                'unique_together': {('user', 'flashcard')},
            },
        ),
        migrations.CreateModel(
            name='CardXPRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_xp_earned', models.IntegerField(default=0)),
                ('last_studied_at', models.DateTimeField(blank=True, null=True)),
                ('progress', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='xp_record', to='study.cardprogress')),
            ],
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('spaced', 'Spaced'), ('cram', 'Cram')], max_length=20)),
                ('cards_target', models.PositiveIntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to='decks.deck')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to='accounts.languagelearner')),
            ],
        ),
        migrations.CreateModel(
            name='CardAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple choice'), ('write_down', 'Write down'), ('match', 'Match'), ('true_false', 'True / false'), ('listening', 'Listening'), ('fill_blank', 'Fill in the blank')], max_length=50)),
                ('is_correct', models.BooleanField(default=False)),
                ('response_ms', models.IntegerField(blank=True, null=True)),
                ('answered_at', models.DateTimeField()),
                ('flashcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_answers', to='decks.flashcard')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_answers', to='study.studysession')),
            ],
        ),
    ]
